import { StyleSheet } from 'react-native';
import { Theme } from '@/types/theme';

export const createProfileStyles = (theme: Theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  scrollView: {
    flex: 1,
  },
  header: {
    padding: 24,
    backgroundColor: theme.colors.primary,
    shadowColor: theme.colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 1,
    zIndex: 1,
  },
  headerTop: {
    flexDirection: "row" as const,
    justifyContent: "space-between" as const,
    alignItems: "center" as const,
    marginBottom: 24,
  },
  headerTitle: {
    fontSize: 28,
    //fontWeight: "800" as const,
    color: theme.colors.textInverse,
    fontFamily: "Inter_900Black",
  },
  themeButton: {
    padding: 8,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 1,
  },
  profileCard: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 16,
  },
  avatarContainer: {
    position: "relative" as const,
  },
  avatarLarge: {
    width: 80,
    height: 80,
    borderRadius: 1,
    backgroundColor: theme.colors.surface,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    borderWidth: 3,
    borderColor: theme.colors.textInverse,
  },
  avatarEmoji: {
    fontSize: 40,
  },
  editBadge: {
    position: "absolute" as const,
    bottom: 0,
    right: 0,
    backgroundColor: theme.colors.accent,
    width: 28,
    height: 28,
    borderRadius: 1,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    borderWidth: 2,
    borderColor: theme.colors.primary,
  },
  userInfo: {
    flex: 1,
  },
  nameContainer: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 8,
  },
  userName: {
    fontSize: 24,
    //fontWeight: "700" as const,
    color: theme.colors.textInverse,
    marginBottom: 4,
    fontFamily: "Inter_900Black",
  },
  userLevel: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.8)',
    fontWeight: "600" as const,
  },
  scrollContent: {
    flexGrow: 1,
    padding: 24,
    gap: 32,
    paddingBottom: 100,
  },
  nameEditContainer: {
    gap: 12,
  },
  nameInput: {
    backgroundColor: theme.colors.surface,
    borderRadius: 1,
    paddingHorizontal: 95,
    paddingVertical: 10,
    fontSize: 18,
    color: theme.colors.text,
    textAlign: "center" as const,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  nameEditButtons: {
    flexDirection: "row" as const,
    gap: 12,
  },
  nameEditButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 1,
    alignItems: "center" as const,
  },
  cancelButton: {
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  saveButton: {
    backgroundColor: theme.colors.primary,
  },
  cancelButtonText: {
    color: theme.colors.text,
    fontSize: 16,
    fontWeight: "600" as const,
  },
  saveButtonText: {
    color: theme.colors.textInverse,
    fontSize: 16,
    fontWeight: "600" as const,
  },
  statsSection: {
    gap: 16,
  },
  sectionTitle: {
    fontSize: 20,
    color: theme.colors.text,
    fontFamily: "Inter_900Black",
  },
  statsGrid: {
    flexDirection: "row" as const,
    gap: 12,
  },
  statCard: {
    flex: 1,
    backgroundColor: theme.colors.surface,
    borderRadius: 1,
    padding: 16,
    alignItems: "center" as const,
    gap: 8,
    borderWidth: 1,
    borderColor: theme.colors.border,
    shadowColor: theme.colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    //elevation: 2,
  },
  statIcon: {
    width: 48,
    height: 48,
    borderRadius: 1,
    backgroundColor: theme.colors.primaryLight,
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  statEmoji: {
    fontSize: 32,
  },
  statValue: {
    fontSize: 24,
    color: theme.colors.text,
    fontFamily: "Inter_900Black",
  },
  statLabel: {
    fontSize: 12,
    color: theme.colors.textSecondary,
    fontWeight: "600" as const,
    textAlign: "center" as const,
  },
  settingsSection: {
    gap: 16,
  },
  settingItem: {
    flexDirection: "row" as const,
    justifyContent: "space-between" as const,
    alignItems: "center" as const,
    backgroundColor: theme.colors.surface,
    borderRadius: 1,
    padding: 16,
    borderWidth: 1,
    borderColor: theme.colors.border,
    shadowColor: theme.colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    //elevation: 2,
  },
  settingLeft: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 12,
    flex: 1,
  },
  settingIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 1,
    backgroundColor: theme.colors.backgroundSecondary,
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  dangerIconContainer: {
    backgroundColor: theme.colors.errorLight,
  },
  settingTitle: {
    fontSize: 16,
    fontWeight: "600" as const,
    color: theme.colors.text,
  },
  settingDescription: {
    fontSize: 13,
    color: theme.colors.textSecondary,
  },
  badgesSection: {
    gap: 16,
    marginBottom: 20,
  },
  badgesGrid: {
    flexDirection: "row" as const,
    flexWrap: "wrap" as const,
    gap: 12,
  },
  badgeItem: {
    backgroundColor: theme.colors.surface,
    borderRadius: 1,
    padding: 16,
    alignItems: "center" as const,
    gap: 8,
    minWidth: 100,
    borderWidth: 1,
    borderColor: theme.colors.border,
    shadowColor: theme.colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    //elevation: 2,
  },
  badgeEmoji: {
    fontSize: 36,
  },
  badgeLabel: {
    fontSize: 12,
    color: theme.colors.text,
    fontWeight: "600" as const,
    textAlign: "center" as const,
  },
  noBadgesText: {
    fontSize: 14,
    color: theme.colors.textSecondary,
    fontStyle: "italic" as const,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    justifyContent: "flex-end" as const,
  },
  modalContent: {
    backgroundColor: theme.colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 40,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    //elevation: 10,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: "700" as const,
    color: theme.colors.text,
    marginBottom: 20,
    textAlign: "center" as const,
  },
  avatarsGrid: {
    flexDirection: "row" as const,
    flexWrap: "wrap" as const,
    gap: 12,
    justifyContent: "center" as const,
  },
  avatarOption: {
    width: 70,
    height: 70,
    borderRadius: 1,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    position: "relative" as const,
    backgroundColor: theme.colors.backgroundSecondary,
  },
  avatarSelected: {
    borderWidth: 3,
    borderColor: theme.colors.primary,
    backgroundColor: theme.colors.primaryLight,
  },
  avatarOptionEmoji: {
    fontSize: 36,
  },
  checkmark: {
    position: "absolute" as const,
    top: -6,
    right: -6,
    backgroundColor: theme.colors.success,
    width: 24,
    height: 24,
    borderRadius: 1,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    borderWidth: 2,
    borderColor: theme.colors.surface,
  },
  checkmarkText: {
    color: "#FFF",
    fontSize: 14,
    fontWeight: "700" as const,
  },
  badgeIcon: {
    width: 40,
    height: 40,
    borderRadius: 1,
    backgroundColor: theme.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  avatarImage: {
    width: 50,
    height: 50,
    borderRadius: 1,
    resizeMode: 'cover',
  },
});